name: Ask your notes frontend

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Manual trigger

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set Image Tags
      id: vars
      run: |
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        SHORT_SHA=$(git rev-parse --short HEAD)
        IMAGE_TAG="${SHORT_SHA}-${TIMESTAMP}"
        FULL_TAG="${DOCKER_USERNAME}/repos:${DOCKER_PROJECT}-${IMAGE_TAG}"
        echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
        echo "FULL_TAG=${FULL_TAG}" >> $GITHUB_ENV
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PROJECT: ${{ vars.DOCKER_PROJECT }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ env.FULL_TAG }}
          ${{ secrets.DOCKER_USERNAME }}/repos:${{ vars.DOCKER_PROJECT }}-latest

    - name: Output Image Tag
      run: echo "Pushed image with tag ${{ env.FULL_TAG }}"
    
    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config

    - name: Update Kubernetes Deployment
      run: |
        kubectl set image -n prod deployment/${{ vars.DOCKER_PROJECT }} ${{ vars.DOCKER_PROJECT }}=${{ env.FULL_TAG }}
